
"Release data, autogenerated from metadata.cfg by setup_common.create_release_file()"
__author__ = "Andy Dustman <adustman@users.sourceforge.net>"
version_info = (1, 3, 0, 'final', 0)
__version__ = "1.3.0"
__revision__ = "$ Revision: $"[11:-2]
